### ISSUE TITLE
Traceback (most recent call last):   File "disco-diffusion/disco.py", line 3091, in <module>     do_run()   File "disco-diffusion/disco.py", line 1432, in do_run     samples = sample_fn( TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'

### ISSUE THREAD

**Issue by fangbo6699** [alembics/disco-diffusion#156]
Traceback (most recent call last):
  File "disco-diffusion/disco.py", line 3091, in <module>
    do_run()
  File "disco-diffusion/disco.py", line 1432, in do_run
    samples = sample_fn(
TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'

**Comment by fangbo6699** [comment]
disco diffusion of docker err,help me
