### ISSUE TITLE
Is it possible to generate using CPU ?

### ISSUE THREAD

**Issue by heiheiheibj** [alembics/disco-diffusion#50]
hello.

I had some trouble with my graphics card though.
when i switch the device to CPU 

HBox(children=(FloatProgress(value=0.0, description='Batches', max=50.0, style=ProgressStyle(description_width='initial')), HTML(value='')))

Output()
  0%|                                                                                          | 0/240 [00:00<?, ?it/s]
Seed used: 896041566
Traceback (most recent call last):
  File "disco.py", line 2533, in <module>
    do_run()
  File "disco.py", line 1338, in do_run
    for j, sample in enumerate(samples):
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 900, in ddim_sample_loop_progressive
    eta=eta,
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 671, in ddim_sample
    model_kwargs=model_kwargs,
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\respace.py", line 91, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\gaussian_diffusion.py", line 260, in p_mean_variance
    model_output = model(x, self._scale_timesteps(t), **model_kwargs)
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\respace.py", line 128, in __call__
    return self.model(x, new_ts, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\tf\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\unet.py", line 656, in forward
    h = module(h, emb)
  File "D:\ProgramData\Anaconda3\envs\tf\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\disco-diffusion/guided-diffusion\guided_diffusion\unet.py", line 77, in forward
    x = layer(x)
  File "D:\ProgramData\Anaconda3\envs\tf\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\tf\lib\site-packages\torch\nn\modules\conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ProgramData\Anaconda3\envs\tf\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: "unfolded2d_copy" not implemented for 'Half'

What should I do ?
thx

**Comment by entmike** [comment]
Known issue apparently.  Reported by others on Discord.  Have not seen anyone able to fix yet.

**Comment by OodavidsinoO** [comment]
I made it worked on the CPU. Here's my repo.
https://github.com/OodavidsinoO/disco-diffusion

**Comment by heiheiheibj** [comment]
OK.thx

**Comment by aletts** [comment]
The option to use the CPU is now in official Disco Diffusion 5.2 too.
