### ISSUE TITLE
ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'

### ISSUE THREAD

**Issue by DreamInSun** [alembics/disco-diffusion#96]
Running 4. Duffise：

Requirement already satisfied: frozenlist>=1.1.1 in c:\programdata\anaconda3\envs\py37\lib\site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning) (1.3.0)

disco_xform_utils.py failed to import InferenceHelper. Please ensure that AdaBins directory is in the path (i.e. via sys.path.append('./AdaBins') or other means).
Using device: cuda:0
512 Model already downloaded, check check_model_SHA if the file is corrupt
Secondary Model already downloaded, check check_model_SHA if the file is corrupt
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\lpips\weights\v0.1\vgg.pth
Starting Run: TimeToDisco(0) at frame 0
Prepping model...
range(0, 1)
None
Frame 0 Prompt: ['A beautiful painting of a singular lighthouse, shining its light across a tumultuous sea of blood by greg rutkowski and thomas kinkade, Trending on artstation.', 'yellow color scheme']
Batches:   0%|          | 0/50 [00:00<?, ?it/s]

Output()
Seed used: 752449851
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.3\plugins\python-ce\helpers\pycharm\docrunner.py", line 305, in <module>
    modules = [loadSource(a[0])]
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.3\plugins\python-ce\helpers\pycharm\docrunner.py", line 237, in loadSource
    module = _load_file(moduleName, fileName)
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.2.3\plugins\python-ce\helpers\pycharm\docrunner.py", line 209, in _load_file
    return machinery.SourceFileLoader(moduleName, fileName).load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:/WorkStation/[AI_Art]/disco-diffusion/disco.py", line 2607, in <module>
    do_run()
  File "D:/WorkStation/[AI_Art]/disco-diffusion/disco.py", line 1350, in do_run
    transformation_percent=args.transformation_percent
TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'

Process finished with exit code 1

**Comment by caymanlee** [comment]
have the same issue since the update of 5.3, using WSL in Win10 connect with local GPU via jypyter interface. before 5.3, all goes well
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [14], in <cell line: 175>()
    174 torch.cuda.empty_cache()
    175 try:
--> 176     do_run()
    177 except KeyboardInterrupt:
    178     pass

Input In [6], in do_run()
    625     init = regen_perlin()
    627 if args.diffusion_sampling_mode == 'ddim':
--> 628     samples = sample_fn(
    629         model,
    630         (batch_size, 3, args.side_y, args.side_x),
    631         clip_denoised=clip_denoised,
    632         model_kwargs={},
    633         cond_fn=cond_fn,
    634         progress=True,
    635         skip_timesteps=skip_steps,
    636         init_image=init,
    637         randomize_class=randomize_class,
    638         eta=eta,
    639         transformation_fn=symmetry_transformation_fn,
    640         transformation_percent=args.transformation_percent
    641     )
    642 else:
    643     samples = sample_fn(
    644         model,
    645         (batch_size, 3, args.side_y, args.side_x),
   (...)
    653         order=2,
    654     )

TypeError: ddim_sample_loop_progressive() got an unexpected keyword argument 'transformation_fn'

**Comment by caymanlee** [comment]
it work, thanks a lot
